### GET localhost:3000
GET http://localhost:3000

### GET all users
GET http://localhost:3000/users

### GET user by query string (if gender specified)
GET http://localhost:3000/users?gender=male

### GET specific user (if ID specified)
GET http://localhost:3000/users/1

### GET user by filter ; not optional
GET http://localhost:3000/users/married/false


### POST create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "id": 10,
    "name": "sfsdfsd",
    "email": "somethsdfsding@email.com",
    "age": 28,
    "gender": "female",
    "isMarried": false
}


### PATCH user
PATCH http://localhost:3000/users
Content-Type: application/json

{
    "id": 1,
    "gender": "female"
}